{% set name = "faster-coco-eval" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/faster_coco_eval-{{ version }}.tar.gz
  sha256: 23d470688ffdb3956ddf23bb22f401d8eb765d51df8afc156bf0d9cf9e58d8ea

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # this is necessary for all compiled recipes
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=42
    - wheel
    - python-build
    - numpy
    - cython
    - pybind11 >=2.12.0
    - pip
  run:
    - python
    - plotly
    - pandas
    - pillow

test:
  imports:
    - faster_coco_eval
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MiXaiLL76/faster_coco_eval
  summary: Faster interpretation of the original COCOEval
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MiXaiLL76
